### ISSUE TITLE
TODO: here_doc execution

### ISSUE THREAD

**Issue by Haliris** [Haliris/minishell#26]
- [x] Free lexer memory after execution so that we can call unlink() on the heredoc->fd for every here_doc tk.

- [x] Make the parser access the heredoc struct in the tokens list to fetch the path of the file and add it to the parser tables.

- [x] Make the execute process distinguish properly open files in append mode when necessary.
