### ISSUE TITLE
TODO list for pre-final version.

### ISSUE THREAD

**Issue by Haliris** [Haliris/minishell#31]
- [x] Test environment variables
- [x] Expanding variables within strings

- [x] Garbage collection refactoring for our main data structures (lexer, parser, here_doc)

- [x] Finish the built-ins
- [x] The functions themselves
- [x] Their implementation within the program

- [ ] Write a test script to check that runs agreed upon commands to check quickly that everything still works.

**Comment by Haliris** [comment]
REALLY check exit built_in behavior in bash.

Exit works fine with numbers signed with + but not with + alone for instance.

**Comment by BenjaminHThomas** [comment]
done :^)
